// Generate React 19 JSX types (src/react.d.ts) from custom-elements.json,
// so the React typings can never drift from the components.
//
// React 19 sets a prop as a property when the element has one, and turns
// `on<event-name>` props into listeners for that exact event name. So each
// element gets: its @property fields, plus `on<name>` for each custom event.
import { readFileSync, writeFileSync } from 'node:fs';

const manifest = JSON.parse(readFileSync('custom-elements.json', 'utf8'));
const elements = manifest.modules
  .flatMap((m) => m.declarations ?? [])
  .filter((d) => d.tagName)
  .sort((a, b) => a.tagName.localeCompare(b.tagName));

const doc = (text, indent) =>
  text ? `${indent}/** ${text.replace(/\s+/g, ' ').replace(/\*\//g, '*\\/')} */\n` : '';

const imports = new Set();
const entries = elements.map((el) => {
  imports.add(el.name);
  const props = [...new Set((el.attributes ?? []).map((a) => a.fieldName).filter(Boolean))];
  const picked = props.length ? `, ${props.map((p) => `'${p}'`).join(' | ')}` : '';
  // Only custom events (with a dash). Native ones like change go through
  // React's own onChange.
  const events = (el.events ?? []).filter((e) => e.name.includes('-'));
  const handlers = events.map((e) => {
    const type = e.type?.text ?? 'CustomEvent';
    if (type !== 'CustomEvent') imports.add(type);
    return `${doc(e.description, '        ')}        'on${e.name}'?: (event: ${type}) => void;\n`;
  }).join('');
  const extra = handlers ? ` & {\n${handlers}      }` : '';
  return `${doc(el.description?.split('\n\n')[0], '      ')}      '${el.tagName}': ElementProps<${el.name}${picked}>${extra};\n`;
});

const out = `// Generated by scripts/react-types.js from custom-elements.json. Do not edit.
//
// JSX types for React 19. Import once, anywhere in a React app:
//   import type {} from '@maxaakre/ui/react';
import type { HTMLAttributes, Ref } from 'react';
import type { ${[...imports].sort().join(', ')} } from './index.js';

/** Standard HTML props, the element's own properties K, and a typed ref. */
type ElementProps<T, K extends keyof T = never> = HTMLAttributes<T> & Partial<Pick<T, K>> & { ref?: Ref<T> };

declare module 'react' {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
${entries.join('')}    }
  }
}
`;

writeFileSync('src/react.d.ts', out);
