// Generated by scripts/react-types.js from custom-elements.json. Do not edit.
//
// JSX types for React 19. Import once, anywhere in a React app:
//   import type {} from '@maxaakre/ui/react';
import type { HTMLAttributes, Ref } from 'react';
import type { UiButton, UiCheckbox, UiCloseEvent, UiDialog, UiDisclosure, UiTab, UiTabChangeEvent, UiTabPanel, UiTabs, UiTextField, UiToggleEvent } from './index.js';

/** Standard HTML props, the element's own properties K, and a typed ref. */
type ElementProps<T, K extends keyof T = never> = HTMLAttributes<T> & Partial<Pick<T, K>> & { ref?: Ref<T> };

declare module 'react' {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      /** A button. Wraps a native `<button>` so keyboard, focus and screen-reader behaviour come from the platform. */
      'ui-button': ElementProps<UiButton, 'variant' | 'size' | 'type' | 'label' | 'disabled'>;
      /** A checkbox with its label. Wraps a native `<input type="checkbox">`, so Space, focus and the checked/mixed announcement come from the platform. */
      'ui-checkbox': ElementProps<UiCheckbox, 'checked' | 'indeterminate' | 'name' | 'value' | 'disabled'>;
      /** A modal dialog. Built on native `<dialog>` and `showModal()`, so the focus trap, the inert background, the top layer and Escape come from the platform. */
      'ui-dialog': ElementProps<UiDialog, 'open' | 'label' | 'closeOnBackdrop'> & {
        /** The user is closing it: Escape, the backdrop (with `close-on-backdrop`), or a `data-dialog-close` button. `detail.returnValue` is the button's value, or `''`. Cancelable: `preventDefault()` keeps it open. Not fired when `open` is set in code. */
        'onui-close'?: (event: UiCloseEvent) => void;
      };
      /** Show and hide a section. Built on native `<details>` and `<summary>`, so the button role, expanded state, Enter/Space and find-in-page come from the platform. */
      'ui-disclosure': ElementProps<UiDisclosure, 'open'> & {
        /** The user opened or closed it. `detail.open` is the new state. Not fired when `open` is set in code. */
        'onui-toggle'?: (event: UiToggleEvent) => void;
      };
      /** One tab. Place it directly inside `<ui-tabs>`. It moves itself into the tab list (it sets `slot="tab"` if you did not). */
      'ui-tab': ElementProps<UiTab, 'selected' | 'value'>;
      /** The content for one tab. Place it inside `<ui-tabs>`, in the same order as the tabs. */
      'ui-tab-panel': ElementProps<UiTabPanel>;
      /** Tabs: one panel visible at a time. Follows the WAI-ARIA tabs pattern with manual activation: arrow keys move focus, Enter or Space selects. */
      'ui-tabs': ElementProps<UiTabs, 'label' | 'selectedIndex'> & {
        /** The user selected a different tab. `detail.index` and `detail.value`. Not fired when `selectedIndex` is set in code. */
        'onui-tab-change'?: (event: UiTabChangeEvent) => void;
      };
      /** A single-line text input with its label, hint and error. */
      'ui-text-field': ElementProps<UiTextField, 'label' | 'hideLabel' | 'value' | 'name' | 'placeholder' | 'required' | 'hint' | 'error' | 'disabled'>;
    }
  }
}
