#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# The captured URL is not a secret, and this app reads no env vars, so keep the
# re-run cache out of the repo. The real record lands on the ticket in stage 6.
ENV_FILE="${TMPDIR:-/tmp}/daily-todo-deploy.env"

REPO_ROOT=$(git rev-parse --show-toplevel)
TICKET="$REPO_ROOT/.scratch/multi-device-sync/issues/01-deploy-to-vercel.md"

banner "Deploy Daily Todo to Vercel"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Pre-flight: is there something to deploy?"
say "Vercel builds from GitHub, so it can only see commits you have pushed."
cd "$REPO_ROOT"

if [[ -n "$(git status --porcelain)" ]]; then
  warn "You have uncommitted changes:"
  git status --short | sed 's/^/    /'
  note "Vercel will deploy what is on the remote, not what is on your disk."
  confirm "Carry on anyway?" || { say "Stopping. Commit and push, then re-run."; exit 0; }
fi

git fetch origin --quiet 2>/dev/null || warn "Could not reach origin; continuing on local state."
if [[ -n "$(git log origin/main..main --oneline 2>/dev/null)" ]]; then
  warn "Local main is ahead of origin/main. Vercel will not see these commits:"
  git log origin/main..main --oneline | sed 's/^/    /'
  confirm "Push them now?" && git push origin main
fi

say "Checking the production build works before Vercel tries it..."
if pnpm build >/dev/null 2>&1; then
  printf '  %s✓%s build clean\n' "$GREEN" "$RESET"
else
  warn "pnpm build FAILED locally. Fix that first: Vercel will fail the same way."
  exit 1
fi
pause "Ready to set up Vercel?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Import the repository into Vercel"
open_url "https://vercel.com/new"
step "Sign in with GitHub if you are not already."
step "Find the repo 'todo-webcomponents' in the list and choose to import it."
note "If it is not listed, there is usually an option to configure/adjust GitHub"
note "App permissions so Vercel can see this repository. Grant it, then come back."
pause "Once you are on the configuration screen for this project, press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Check the build settings before deploying"
say "Vercel should detect this as a Vite project on its own. Verify, do not assume."
step "Root directory should be:   apps/daily-todo"
step "Framework preset should be: Vite"
step "Build command should be:    pnpm build"
step "Output directory should be: dist"
step "Install command can stay on the default (it respects the pinned pnpm version)."
note "Exact labels move around in Vercel's UI; match the meaning, not the wording."
note "Leave Environment Variables empty. This app reads none, by design."
warn "If it guessed a different framework, override it rather than accepting it."
pause "Settings look right?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Deploy, and capture the URL"
step "Press Deploy, and wait for the build to finish."
note "The build is small: about 9.9 kB gzipped. It should take well under a minute."
say ""
say "When it succeeds, Vercel shows the deployment and its production domain."
step "Copy the production URL (the .vercel.app one, not a preview or a build log URL)."
ask VERCEL_PROD_URL "Paste the production URL:"

if [[ -z "${VERCEL_PROD_URL:-}" ]]; then
  warn "No URL captured. Re-run the wizard once the deploy has finished."
  exit 1
fi
[[ "$VERCEL_PROD_URL" == http* ]] || VERCEL_PROD_URL="https://$VERCEL_PROD_URL"
write_env VERCEL_PROD_URL "$VERCEL_PROD_URL"

say ""
say "Confirming the deployment is actually reachable..."
if command -v curl >/dev/null 2>&1; then
  code=$(curl -s -o /dev/null -w '%{http_code}' -L --max-time 15 "$VERCEL_PROD_URL" || echo "000")
  case "$code" in
    200) printf '  %s✓%s %s returned 200\n' "$GREEN" "$RESET" "$VERCEL_PROD_URL" ;;
    401|403) warn "Got $code. Deployment Protection is probably on — a phone will be asked to log in." ;;
    000) warn "Could not reach it. Check the URL, or the deploy may still be building." ;;
    *)   warn "Got HTTP $code. Worth looking at before you try the phone." ;;
  esac
else
  note "curl not available; skipping the reachability check."
fi
pause ""

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Open it on your phone"
say "This is the whole point of the ticket: a second, real device."
say ""
printf '  %s%s%s\n' "$BOLD" "$VERCEL_PROD_URL" "$RESET"
say ""
if command -v qrencode >/dev/null 2>&1; then
  qrencode -t ANSIUTF8 "$VERCEL_PROD_URL" || warn "qrencode failed; use the URL above."
  step "Scan the code above with your phone camera."
else
  note "No 'qrencode' installed, so no QR code here."
  note "For one, either: brew install qrencode"
  note "            or: pnpm dlx qrcode-terminal '$VERCEL_PROD_URL'"
  step "Otherwise just type the URL into your phone, or message it to yourself."
fi
warn "Use Safari on an iPhone. Ticket 07 is about WebKit's storage rules, and"
warn "Chrome on iOS runs on WebKit too — so test the engine you will actually ship to."
pause "App loaded on the phone?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Sanity-check, and record the result"
say "Quick pass on the phone. You are not reviewing the design here — ticket 02"
say "does that properly. You are checking the deploy is real and usable."
step "Add a task. Does the composer work with the on-screen keyboard?"
step "Reload the page. Does the task survive? (localStorage on the phone.)"
step "Check dark mode matches the phone's setting."
step "Note whether the Triage two-pane layout is even reachable — ticket 02's problem."
say ""

if [[ -f "$TICKET" ]]; then
  {
    printf '\n'
    printf '**%s, from the deploy wizard.** Production URL: <%s>\n\n' "$(date +%Y-%m-%d)" "$VERCEL_PROD_URL"
    printf 'Deployed from `main` via the Vercel GitHub integration, so pushes redeploy.\n'
    printf 'Static build only — no server, no database, no auth. Each device keeps its own\n'
    printf 'independent `localStorage` list, which is the problem this map exists to solve.\n'
  } >> "$TICKET"
  printf '  %s✓ recorded%s the URL on ticket 01\n' "$GREEN" "$RESET"
else
  warn "Could not find ticket 01 at $TICKET — record the URL there by hand."
fi

say ""
say "Next: tell your agent the URL, and ask it to resolve ticket 01 and unblock"
say "tickets 02 (Triage on a phone) and 07 (offline on the phone)."

finish
